name: Deploy to S3
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v3

        - name: Run build script
          run: |
            ./build.sh

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket-region: "us-east-2"
            bucket: "codecraftersconsulting.com"
            # dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            # invalidation: /
            # delete-removed: true
            # no-cache: true
            # private: true
            # files-to-include: ".*/*,*/*,**"
