name: Deploy to S3
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Run build script
          run: |
            ./build.sh

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

        - name: Deploy to S3
          run: |
            aws s3 sync build/ s3://codecraftersconsulting.com --delete
            # Uncomment the next line if you want to invalidate CloudFront
            # aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
